apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  namespace: kubeflow-user-example-com
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/workspace-pv"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-pv
  namespace: kubeflow-user-example-com
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/vol-pv"
    type: DirectoryOrCreate
